warp-ds/css

CONTRIBUTING.md
README.md
index.js
resets/resets.js

fix: add readme and restructured output files

---

resets/resets.js

[WARP-80](https://nmp-jira.atlassian.net/browse/WARP-80): Remove button reset.  It breaks fabric buttons and pills.

fix: remove button reset [WARP-80]

---

component-classes/vite.config.js

Before|After
---|---
Tests in React
Before|After
---|---

fix: add type declarations to the dist folder

---

component-classes/index.d.ts
component-classes/index.js

fix: toggle bugs

---

tokens/blocket.se/combobox.yml
tokens/blocket.se/semantic.yml
tokens/finn.no/combobox.yml
tokens/finn.no/semantic.yml
tokens/tori.fi/combobox.yml
tokens/tori.fi/semantic.yml

Updated names and values of semantic tokens according to changes in this document (greens added or changed, reds deleted):
https://docs.google.com/spreadsheets/d/1Q-Tr_dwJVfxgh3527IFjXQKqtnPPM42QeIr-M6q-zu8/edit?pli=1#gid=888578831

fix: Updated misc names and values of semantic tokens

---

component-classes/index.js
tokens/blocket.se/toast.yml
tokens/finn.no/toast.yml
tokens/tori.fi/toast.yml

https://nmp-jira.atlassian.net/jira/software/projects/WARP/boards/15?selectedIssue=WARP-57

fix: Add tokens for the close icon in the Toast component

---

component-classes/index.d.ts
component-classes/index.js

Figma: https://www.figma.com/file/8P1JQsd82b93gQ6K3igO2p/Warp---Components?type=design&node-id=381-42423&mode=design&t=guVpej3e17aPbmb6-0

feat: Add component-classes for Badge

---

.github/renovate.json
.github/workflows/release.yml
.github/workflows/update-next.yml
CHANGELOG.md
LICENSE
component-classes/classes.d.ts
component-classes/index.js
component-classes/vite.config.js
package.json
pnpm-lock.yaml

Fixes are listed in the commit history. They will also be included in the release notes.

Release 1.1.1

---

.github/workflows/release.yml

I guess this is applicable now, right?

fix: release of v2

---

CHANGELOG.md
component-classes/index.js
package.json
pnpm-lock.yaml

Fixes are listed in the commit history. They will also be included in the release notes.

Release 1.1.2

---

component-classes/index.js

Background: https://nmp-jira.atlassian.net/jira/software/projects/WARP/boards/15?selectedIssue=WARP-349
Before|After
---|---

fix: fix modal sorting problem in pill button

---

CHANGELOG.md
component-classes/index.d.ts
component-classes/index.js
package.json

We need this out to complete [Attention close button task](https://nmp-jira.atlassian.net/browse/WARP-362).

Release 1.3.0

---

component-classes/classes.js

chore: Deduplicate component class names

---

resets/resets.js

fix: revert "fix: add style to a-tag in resets.js"

---

tokens/finn.no/pill.yml
tokens/tori.fi/pill.yml

For reference: https://docs.google.com/spreadsheets/d/1Q-Tr_dwJVfxgh3527IFjXQKqtnPPM42QeIr-M6q-zu8/edit#gid=1588196525&range=C304

fix: Changed to slightly lighter colors for the suggestion pill

---

component-classes/index.d.ts
component-classes/index.js

This is for [WARP-135](https://nmp-jira.atlassian.net/browse/WARP-135)

feat: Add classes for the pagination component

---

component-classes/index.d.ts
component-classes/index.js

Fixes [WARP-501](https://nmp-jira.atlassian.net/jira/software/projects/WARP/boards/15?assignee=61f9360dc224b80069c7f536&selectedIssue=WARP-501)
After some more discussions around Pagination, a few more issues were raised. These updates will make it possible to apply all fixes in https://github.com/warp-ds/react/pull/206.

fix(cc): fix pagination classes

---

component-classes/index.d.ts
component-classes/index.js

https://sch-chat.slack.com/archives/C04P0GYTHPV/p1709545888447519

fix: Add class for Expandable info variant

---

component-classes/index.d.ts
component-classes/index.js
package.json
pnpm-lock.yaml

- Fixes issues with hover and active background colors for Card and Box components

fix: Update Box and Card to use new surface concept

---

component-classes/index.js

As described in this thread: https://sch-chat.slack.com/archives/C04P0GYTHPV/p1711460113008609

fix: Resolved underline issues in Button component

---

component-classes/index.d.ts
component-classes/index.js

Fixes needed after introducing surface concept.
Also better structured classes and removal of a lot of unused/unnecessary css classes.

fix: Updates for Card (and Expandable box) component classes

---

component-classes/index.d.ts
component-classes/index.js
resets/index.js
resets/resets.js
tokens/blocket.se/buttons.yml
tokens/blocket.se/semantic.yml
tokens/dba.dk/buttons.yml
tokens/dba.dk/semantic.yml
tokens/finn.no/buttons.yml
tokens/finn.no/semantic.yml
tokens/tori.fi/buttons.yml
tokens/tori.fi/semantic.yml

- fix(badge): remove deprecated notification variant classes
- fix(box): remove clickable box classes
- fix(cc): remove all deprecated classes
- fix(resets): remove deprecated resets.min.css
- fix(resets): remove deprecated tokens
- fix(ribbon): remove deprecated ribbon component classes
- fix(card): remove deprecated CardUnselected class from card component
- fix(switchtoggle): remove deprecated switch class
- fix(modal): remove deprecated transparentBg class from modal component
- fix(label): remove deprecated labelInvalid class from label component
- fix(helptext): remove deprecated helpTextValid and helpTextInvalid classes from helpText component
- fix(semantic): remove s-color-border-focused from semantic.yml
- fix(semantic): remove duplicate_as_rgb flag from semantic.yml
- …

fix: remove deprecated tokens and classes

---

component-classes/index.js

https://nmp-jira.atlassian.net/browse/WARP-682.

fix: WARP-682 slider css

---

CHANGELOG.md
component-classes/index.d.ts
component-classes/index.js
package.json

Release 2.1.1

---

tokens/neutral.com/avatar.yml
tokens/neutral.com/base.yml
tokens/neutral.com/buttongroup.yml
tokens/neutral.com/dark/buttons.yml
tokens/neutral.com/dark/icons.yml
tokens/neutral.com/deprecated.yml
tokens/neutral.com/light/buttons.yml
tokens/neutral.com/light/icons.yml
tokens/neutral.com/semantic.yml
tokens/neutral.com/shadows.yml
tokens/vend.com/avatar.yml
tokens/vend.com/base.yml
tokens/vend.com/buttongroup.yml
tokens/vend.com/dark/buttons.yml
tokens/vend.com/dark/icons.yml
tokens/vend.com/deprecated.yml
tokens/vend.com/light/buttons.yml
tokens/vend.com/light/icons.yml
tokens/vend.com/semantic.yml
tokens/vend.com/shadows.yml
utils.js

Adding Neutral and Vend themes to WARP

feat: add new token configurations for vend and neutral themes

---

CHANGELOG.md
package.json
tokens/neutral.com/avatar.yml
tokens/neutral.com/base.yml
tokens/neutral.com/buttongroup.yml
tokens/neutral.com/dark/buttons.yml
tokens/neutral.com/dark/icons.yml
tokens/neutral.com/deprecated.yml
tokens/neutral.com/light/buttons.yml
tokens/neutral.com/light/icons.yml
tokens/neutral.com/semantic.yml
tokens/neutral.com/shadows.yml
tokens/vend.com/avatar.yml
tokens/vend.com/base.yml
tokens/vend.com/buttongroup.yml
tokens/vend.com/dark/buttons.yml
tokens/vend.com/dark/icons.yml
tokens/vend.com/deprecated.yml
tokens/vend.com/light/buttons.yml
tokens/vend.com/light/icons.yml
tokens/vend.com/semantic.yml
tokens/vend.com/shadows.yml
utils.js

Release 2.2.0

---

resets/resets.js

Add focus-visible to all links on Vend

fix: add focus-visible styles for anchor elements in resets.js

---

CHANGELOG.md
package.json
resets/resets.js

Release 2.2.1
