warp-ds/css

.github/workflows/release.yml, resets/resets.js
Some styles should only be applied to the document body and some to both body and web components' shadow host (`:host`).
I've also set the github action dependency versions to align with other setups in @warp-ds org.
=> fix(resets.js): remove redundant styles from :host

resets/resets.js
We used Tailwind's reset with 'inherit' values, but we should use a reset from [fabric](https://github.com/fabric-ds/css/blob/01fd80a27461cf0d593911e974853f84963d0681/src/utils/tailwind/headings.js#L27) that would set headings' font-weight to 700 instead. The issue was reported by a team responsible for the [security page on Finn](https://www.finn.no/min-finn/sikkerhet).
Before:
After:
=> fix(resets.js): apply font-weight 700 to h1-h6

tokens/blocket.se/semantic.yml, tokens/finn.no/semantic.yml, tokens/tori.fi/semantic.yml
Updated the semantic background tokens with new darker colors and moved the former ones to new subtle sub token variants (e.g. former `color-background-positive-hover` would now be `color-background-positive-subtle-hover`).
=> fix: Updated semantic tokens for backgrounds

tokens/blocket.se/focus.yml, tokens/finn.no/focus.yml, tokens/tori.fi/focus.yml
To be merged after: https://github.com/warp-ds/drive/pull/139
=> fix: Remove old token for focus outlines

component-classes/classes.d.ts, component-classes/shortcuts.d.ts, component-classes/tsconfig.json, package.json
While updating our component framework packages I've noticed that we are not adding all the types needed. Both `classes` and `shortcuts` should also be exported with corresponding type declarations. I've struggled here a bit as I got a lot of errors. Specifically one that is described very good [here](https://www.codejam.info/2021/10/typescript-cannot-write-file-overwrite-input.html) 
Before|After
---|---
=> fix: update types, add new for shortcuts and classes

package.json, pnpm-lock.yaml, tokens/index.js
We shouldn't use @import rule with urls due to performance issues. More info in this article: https://www.debugbear.com/blog/avoid-css-import#:~:text=Why%20does%20CSS%20%40import%20slow,can%20download%20them%20in%20parallel
Fixes [WARP-12: Use inline font-face declarations in brand CSS files](https://nmp-jira.atlassian.net/browse/WARP-12)
=> fix(tokens): process @import rule to inline font definitions in brand CSS files

resets/resets.js
We now have a semantic placeholder text color token, so it might be the time to replace any hex values with respective CSS vars in the resets.js.
=> fix(resets.js): use semantic placeholder color token instead of hex

component-classes/index.js
After the button resets fix we need explicitly set background on certain buttons.
Background: https://nmp-jira.atlassian.net/browse/WARP-157, #48 reported here https://docs.google.com/spreadsheets/d/1e-5Or9pbODAneBEIUIqwXrZ08PQ-8qVXawpEvBzPXQU/edit#gid=909319889
=> fix: certain buttons needs transparent background

component-classes/index.js
Fixes outline of button and anchor variants of Clickable.
[Warp-178](https://nmp-jira.atlassian.net/browse/WARP-178?atlOrigin=eyJpIjoiYjFhMTg0MmJkZmU4NDJhZmEzMDg0Y2E5ZWJjYTk3NGIiLCJwIjoiaiJ9)
Before:
After:
=> fix(component-classes): export focusable class of clickable component

component-classes/index.js
=> fix(component-classes): add bg-transparent to clickableNotToggle

tokens/blocket.se/colors.yml, tokens/blocket.se/deprecated.yml, tokens/finn.no/colors.yml, tokens/finn.no/deprecated.yml, tokens/tori.fi/colors.yml, tokens/tori.fi/deprecated.yml
Some apps will still use an [old version of resets.css](https://assets.finn.no/pkg/@warp-ds/css/1.0.0-alpha.7/resets.css) in production before we bump the aliased version of @warp-ds/css from current `1.0.0-alpha.7` to `1.0.0-alpha.27` (or `1.0.0` when that is available). That CSS relies on old color tokens (like `--w-color-background`, `--w-color-text`) that were removed in favour of semantic color tokens. In order for layouts to use the new semantic tokens and then let podlet apps safely align with the other dependencies and stylesheets, we need to ensure backward compatibility of the tokens for some time. 
- [fix: Remove old token for focus outlines](https://github.com/warp-ds/css/commit/1d54f775fda04952a827f9ca756484ac49614d8f)
- [fix: Cleaned out old token files with duplicated or …
=> fix(tokens): restore deprecated foundation/background/outline color tokens

component-classes/index.d.ts, component-classes/index.js
- move bg-transparent to clickable.button and add focusable class
- fix similar issue with background color in Tabs and Buttons
- rename clickable classes to align the Clickable component in React & Vue
**Button group**
**Clickable Box**
**Tabs**
=> fix: transparent background in Clickable, Tabs, Buttons

component-classes/index.js
After adding support to arbitrary `leading` classes in `@warp-ds/uno@alpha.49`, `leading-[24]` on buttons started working, overriding some line-height values. Therefore `text-xs` class on `buttonSmall` now has an important rule which prevents `leading-[24]` from setting a wrong line-height on small buttons.
Before:
After:
=> fix(cc-button): make text-xs override leading-[24] on small buttons

package.json, pnpm-lock.yaml, tokens/index.js
Fixes [WARP-202](https://nmp-jira.atlassian.net/browse/WARP-202?atlOrigin=eyJpIjoiMGIzYzIzNWFkMWM3NDlhZmExYWE5ZjQ3OGU1ODNhOWIiLCJwIjoiaiJ9)
Although fonts follow brands, we want to load font definitions separately from the brand CSS. The reason is that fonts are highly unlikely to change compared to the brand file and loading them as a separate CSS file from `https://assets.finn.no/pkg/@warp-ds/fonts/v1` allows browsers to keep this file cached, which ensures fonts are available as fast as possible on a page.
=> fix(tokens): remove inlined fonts from brand CSS

resets/index.js
We should be consistent and always publish minified css files, without `min` in the file name. As there might still be some apps that are requesting `resets.min.css`, we must keep the deprecated file. Once we know this file is no longer requested, we should remove it from the build.
=> fix(resets): publish only minified versions of css

README.md
After the removal of the `resets.css` and renaming of the `resets.min.css` we don't need to mention those in README anymore. Adjust Usage a bit
=> chore: remove mentions of the old file urls

.github/workflows/release.yml, .github/workflows/update-next.yml, .releaserc.json, CONTRIBUTING.md, README.md
[WARP-209](https://nmp-jira.atlassian.net/browse/WARP-209): Update `contributing.md` file after we change from using alpha to next branch + update github workflows to use `next` instead of `alpha`
=> chore: use 'next' instead of 'alpha'

tokens/blocket.se/buttons.yml, tokens/finn.no/buttons.yml, tokens/tori.fi/buttons.yml
Consulted with @adidick.
All button variants use the same disabled tokens so the `disabled-quiet-` tokens can be removed. They weren't in use so it's  not a breaking change.
=> fix(buttons.yml): remove unused color-button-disabled-quiet- tokens

component-classes/index.js
Affixes that are not interactive should have `cursor: default;`, while `label.label` classes that were used before would include `cursor-pointer`. This PR fixes it by setting `cursor-default` on suffix and prefix `label` classes. When an affix is interactive, it renders as button, which then gets `cursor: pointer;` by default, so we don't need to do anything here.
Not referencing `label.label` classes allowed to remove the `!` rules from `text-xs` and `pb-0`, too. This way we have more control over the applied styles.
Before:
After
=> fix: set cursor to default for non-interactive affixes

README.md
Before:
After:
I thought it's better to show that we have an alias (v1) in Eik. That should prevent people from using specific versions by default. If for some reason they need a specific version, they'll replace that v1, I believe.
=> chore(readme.md): show Eik urls pointing at v1

component-classes/vite.config.js
We have removed `skipPreflight` options since before, need to use `skipResets` instead
Before|After
---|---
=> fix: skip resets in components.css

component-classes/index.js
Alert title should be a heading to ensure accessibility. In @warp-ds/vue Alert accepts a title prop, which will now be a `h3` instead of a `p` with bold font-weight, so in order for that to have the same size as `p`, we need to assign that heading element a 'text-s' class.
A corresponding fix is on its way in @warp-ds/vue once this PR is merged and released.
=> fix(alert): override font-size/line-height of h3 title in Vue Alert

component-classes/index.d.ts, component-classes/index.js
Have to adjust the padding and font-size since we are replacing the inline-svg in the pill-component with a letter 'x'.
Test by linking to branch `refactor/replace-inline-svgs-with-warp-icons` in vue-repo and react-repo:
vue-repo:  https://github.com/warp-ds/vue/pull/78
React-repo: https://github.com/warp-ds/react/pull/95
=> refactor: adjust padding + font-size for ccPill.close

component-classes/index.js
Fixes [WARP-343](https://nmp-jira.atlassian.net/browse/WARP-343)
Tested in React with `npm link` and it looks correct now.
**Before:**
**After:**
=> fix(button): set p-0 on any button of type link

component-classes/index.js
FIxes [WARP-347](https://nmp-jira.atlassian.net/browse/WARP-347)
Buttons rendered as links will now have the text centered.
Example from React:
Before:
After:
=> fix(button): add text-center to buttonAsLink

component-classes/index.d.ts, component-classes/index.js
Adds classes used in an Attention component of `highlight` variant. They reuse callout tokens because we may soon go away from the component level tokens, and adding another component token type isn't necessary.
=> feat(component-classes): add 'highlight' variant to attention classes

component-classes/index.d.ts, component-classes/index.js
The main change was to add `flex` and `items-start` to `attention.base` and `attention.closeBtn` classes.
The end result looks like this:
=> feat(attention): add close button classes

component-classes/index.js
Fix for issue described here: https://sch-chat.slack.com/archives/C04P0GYTHPV/p1698925146375969
(Suggested by @pearofducks 🙏 )
=> fix: Only show focus indicator in Expandable component on focus-visible

component-classes/index.js
left align all tabs. Tabs should no longer be stretched to full width, existing ones should rather be left aligned. This is also a accessability gain for people running extreme magnification.
=> fix(tabs): left align all tabs instead of stretch

component-classes/index.d.ts, component-classes/index.js
Whenever we need to replace a unique class from the component classes list, we should make sure it doesn't break apps that rely on that class being styled until @warp-ds/css dependency is updated. This can happen when those apps get styles from `components.css` available on Eik under https://assets.finn.no/pkg/@warp-ds/css/v1/components.css.
=> fix(cc): restore styles for deprecated z-20 class

tokens/blocket.se/semantic.yml, tokens/finn.no/semantic.yml, tokens/tori.fi/semantic.yml
Fixes [WARP-398](https://nmp-jira.atlassian.net/browse/WARP-398):
We should allow users to style the color of the outline in the same way as they can style border - using semantic color classes. We can for the time being reuse border color tokens, but since the focused outline color is currently assigned to a generic `--w-s-color-focused` token, we thought it’s better to have it as  `--w-s-color-border-focused` to make the border and outline color rules aligned.
We're keeping the generic `focused` token for backward compatibility.
=> fix(tokens): move focused color to border-focused token

component-classes/index.d.ts, component-classes/index.js
After releasing https://github.com/warp-ds/css/pull/89 to [eik](https://assets.finn.no/pkg/@warp-ds/css/v1/components.css) we removed styles for `right-16` and `left-8` classes. This broke styles of expandable's chevron (@warp-ds/elements) that still imports the old classes while pulling styles from Eik. The result looks like this:
This PR restores the two classes as part of the backward compatible list.
=> fix(cc): Restore styles for deprecated right-16 left-8

CHANGELOG.md, component-classes/index.d.ts, component-classes/index.js, package.json, resets/resets.js, tokens/blocket.se/semantic.yml, tokens/finn.no/semantic.yml, tokens/tori.fi/semantic.yml
We should update [components.css](https://assets.finn.no/pkg/@warp-ds/css/1.4.1/components.css) that no longer includes styles for `right-16` and `left-8` classes. We accidentally introduced a breaking change, which this release will fix.
=> Release 1.4.2

package.json
Fixes [WARP-425](https://nmp-jira.atlassian.net/browse/WARP-425)
This change will make it possible to publish assets from this package to Eik using an external repo ([eik-shared-libs](https://github.com/finn-no/eik-shared-libs)).
Note: When eik publishing of the css package is handled in eik-shared-libs (`warp-ds-css` is added to [the list of packages there](https://github.com/finn-no/eik-shared-libs/tree/main/packages)), we will be able to remove all references to Eik from this package. Until then, we can carry out Eik publishing through the Release workflow as before.
=> fix(package.json): publish /dist folder to NPM

component-classes/index.d.ts, component-classes/index.js
Fixes [WARP-430](https://nmp-jira.atlassian.net/browse/WARP-430)
Background color of a on-flat Card will no longer be inherited from the parent container.
A new key was introduced in the `card` component-classes object, because we can't set multiple classes that control background on the same element (i.e. `s-bg` and `i-bg-$color-card-background-selected`). Those selectors will have the same specificity, which could lead to `s-bg` style being applied in a selected card. In our component repos `cardSelected` and `cardUnselected` classes should be applied conditionally for non-flat cards.
Before:
After:
=> fix(cc): set default background on unselected card

component-classes/index.d.ts, component-classes/index.js
Fixes JIRA ticket: [WARP-429](https://nmp-jira.atlassian.net/browse/WARP-429)
- Replaced `h-40 sm:h-48` with `min-h-40 sm:min-h-48`
- Added `py-8` to give the `title` more space
- Replaced `items-center` with `items-start` on `title`
- Added `h-40 sm:h-48 items-center` to `backwardsCompatibleClasses`
=> fix: adjust padding and height for modal title

component-classes/index.d.ts, component-classes/index.js
Fixes JIRA ticket: [WARP-409](https://nmp-jira.atlassian.net/browse/WARP-409)
- Replaced `pt-4 pb-6 text-m!` with `py-10`, due to that we are replacing the letter `X` with the `IconClose16` in our Pill component.
- Updated `backwardsCompatibleClasses` to also include `pt-4 pb-6 text-m!`
**To test:**
Link this branch with the following branch in either our vue or react-repo: `fix/replace-x-with-icon`
=> fix: adjust pill close style

component-classes/index.js
Fix related to JIRA ticket: [WARP-409](https://nmp-jira.atlassian.net/browse/WARP-409)
After being informed that the new design for pill will use an icon with size 16px, the padding-top and padding-bottom of the pill close needed to adjust its size from `py-10` to `py-8`
=> fix: adjust padding-top and padding-bottom for pill close

.github/workflows/lint.pr.yaml, package.json
This PR adds a Github Action workflow for checking linting errors in PRs. As a next step we could consider adding a [husky](https://typicode.github.io/husky/getting-started.html) hook for automatic lint fixing before each commit, so we always commit properly formatted changes.
=> chore(workflows): run Lint workflow in pull requests

component-classes/index.d.ts, component-classes/index.js, tokens/blocket.se/breadcrumbs.yml, tokens/blocket.se/deprecated.yml, tokens/finn.no/breadcrumbs.yml, tokens/finn.no/deprecated.yml, tokens/tori.fi/breadcrumbs.yml, tokens/tori.fi/deprecated.yml
- Use semantic classes (`s-text`) directly instead of component token classes (`i-text-$token`)
- Deprecate redundant component tokens and classes
=> fix: Deprecate redundant Breadcrumbs component tokens and classes

component-classes/index.d.ts, component-classes/index.js, package.json, pnpm-lock.yaml, tokens/blocket.se/badge.yml, tokens/blocket.se/buttons.yml, tokens/blocket.se/colors.yml, tokens/blocket.se/deprecated-defs.yml, tokens/blocket.se/deprecated.yml, tokens/blocket.se/semantic.yml, tokens/blocket.se/spinner.yml, tokens/finn.no/badge.yml, tokens/finn.no/buttons.yml, tokens/finn.no/colors.yml, tokens/finn.no/deprecated-defs.yml, tokens/finn.no/deprecated.yml, tokens/finn.no/semantic.yml, tokens/finn.no/spinner.yml, tokens/tori.fi/badge.yml, tokens/tori.fi/buttons.yml, tokens/tori.fi/colors.yml, tokens/tori.fi/deprecated-defs.yml, tokens/tori.fi/deprecated.yml, tokens/tori.fi/semantic.yml, tokens/tori.fi/spinner.yml
This makes use of changes introduced in https://github.com/warp-ds/tokenizer/pull/3
=> fix: Deprecate old hard coded rgba tokens and change to use new alpha modifier in tokenizer

component-classes/index.js
Added important to bg-transparent to override the default s-bg.
Added important to border-0 as a precaution, since it is only luck that it overrides the default border-1 now.
Removed s-text as that is already added through default.
Solves: https://nmp-jira.atlassian.net/browse/WARP-507 ( https://sch-chat.slack.com/archives/C04P0GYTHPV/p1708939611865719 )
=> fix: Fix transparent background for readonly textfields

component-classes/index.js
Missed one important class when cleaning up Toggle component classes.
Before:
After:
=> fix(cc): restore missing checkmark class for backwards compatibility

component-classes/index.js
Fixes [WARP-340](https://nmp-jira.atlassian.net/browse/WARP-340)
Changes based on the [Figma component library](https://www.figma.com/file/oHBCzDdJxHQ6fmFLYWUltf/Warp---Components-2.0?type=design&node-id=381-40600&mode=design&t=3zNbTFLWoztqzMDE-0):
- outline color is set to s-border-negative when `input` or `select` element is in invalid state
- border color is set to s-border-negative-hover when invalid `input` or `select` element is hovered
- additionally, border-radius was set to 4px for prefix/suffix elements to make their focus outline align with input outline.
=> fix(cc-input/select): fix outline color in invalid state

resets/resets.js, tokens/blocket.se/base.yml, tokens/blocket.se/deprecated-defs.yml, tokens/finn.no/base.yml, tokens/finn.no/deprecated-defs.yml, tokens/tori.fi/base.yml, tokens/tori.fi/deprecated-defs.yml
Deprecate decoration-text-link token and make hovered links have underline, for all brands, through the resets css.
https://nmp-jira.atlassian.net/browse/WARP-508
=> fix: Hovered links should have underline, for all brands, through the resets css

component-classes/index.d.ts, component-classes/index.js
Fixes [WARP-515](https://nmp-jira.atlassian.net/browse/WARP-515)
Changes based on the [Figma component library](https://www.figma.com/file/oHBCzDdJxHQ6fmFLYWUltf/Warp---Components-2.0?type=design&node-id=954-37013&mode=design&t=NPcTtpnw8dXLMG36-0):
- label color doesn't change when input is invalid
- label optional should have subtle text color (the other changes to label optional should be handled in a separate task)
- helpText color should be negative when input is invalid
- there is no use for positive helpText, so it was removed
=> fix(cc): fix label and helpText colors

tokens/tori.fi/semantic.yml
=> fix: New semantic icon colors for hover and active states in Tori

.github/workflows/lint.pr.yaml, .github/workflows/release.yml, component-classes/index.d.ts, component-classes/index.js, package.json, pnpm-lock.yaml
Clean up `input` component classes to avoid buggy style overriding when utility classes styling the same CSS properties are applied to the same element
- Update @warp-ds/uno to 1.12.0 in order to handle padding classes with arbitrary values that contain CSS variables (e.g. `pl-[var(--w-prefix-width,_40px)]`.
- Refactor component classes to avoid style overriding
- Move deprecated classes to `backwardsCompatibleClasses`
Tested with TextField and TextArea in @warp-ds/react, @warp-ds/vue and @warp-ds/elements.
=> fix(cc-input): avoid style overriding

.github/workflows/lint.pr.yaml, .github/workflows/release.yml, package.json
After having an internal discussion we agreed that we should update the `pnpm` version the github action runner will install to v9, and remove the `"packageManager": "pnpm@9.0.6"`  from `package.json`. All contributors will need to update `pnpm` to v9 with `pnpm add -g pnpm` in order to align with the lockfile versions. We've chosen this path with a hope that there will be no more actions required for a long period of time, i.e. until a new major version of `pnpm` creates a breaking change in the lockfiles, which could cause the CI jobs to fail. If we experience that this sort of maintenance is not working too well over time and we see no better way to solve it, we agreed to reconsider the use of [asdf](https://asdf-vm.com/) or [direnv](https://direnv.net/) in order to align the version …
=> chore: update pnpm to v9

component-classes/index.d.ts, component-classes/index.js
This PR ensures no classes styling the same CSS properties are being set on the same HTML element in the Tabs component.
Additionally, this PR fixes [WARP-488](https://nmp-jira.atlassian.net/browse/WARP-488) by restoring a bottom border of subtle gray for the whole Tabs wrapper.
Tested the changes in @warp-ds/react and @warp-ds/vue (`203-fixtabs-clean-up-classes` branch)
React:
Vue:
=> fix(tabs): clean up classes

tokens/blocket.se/icons.yml, tokens/finn.no/icons.yml
The rule for `.list-checked` (created in Drive) expects `var(--w-icon-list-checked)` and not ~~var(--w-icon-list-check)~~.
=> fix: Fixed list-checked icon token name for Finn

component-classes/index.d.ts, component-classes/index.js
Fixes [WARP-472](https://nmp-jira.atlassian.net/browse/WARP-472)
Component classes needed for merging https://github.com/warp-ds/elements/pull/158
Note: we wanted to test out using modal classes directly in @warp-ds/elements and relying on UnoCSS to generate styles from there, but we have encountered some issues with the build setup and WarpElement exposing too many stylesheets. This opened a discussion with the platform web team, which showed we need some more testing to approach component styling in an optimal way.
=> feat: add classes for modal element

component-classes/index.d.ts, component-classes/index.js
This PR ensures no classes styling the same CSS properties are being set on the same HTML element in the `ButtonGroup` component.
**Changes:**
- Renamed and restructured `buttonGroupItem` classes for better readability
Tested the changes in @warp-ds/vue (`fix/cleanup-button-group-classes` branch)
=> fix(buttongroup): clean up classes

component-classes/index.d.ts, component-classes/index.js
This PR ensures no classes styling the same CSS properties are being set on the same HTML element in the Step and Steps components.
**Changes:**
- Renamed `step` and `steps` classes for better readability
Tested the changes in @warp-ds/react and @warp-ds/vue (`fix/clean-up-step-classes` branch)
=> fix: clean up step and steps classes

component-classes/index.d.ts, component-classes/index.js
This PR ensures no classes styling the same CSS properties are being set on the same HTML element in the `Toast` component.
**Changes:**
- Renamed `toast` classes for better readability
- Removed redundant use of `w-full` in `base` class (previously named `toast` class).
Tested the changes in @warp-ds/elements (`fix/clean-up-toast-classes` branch)
=> fix(toast): clean up classes

component-classes/index.d.ts, component-classes/index.js
This PR ensures no classes styling the same CSS properties are being set on the same HTML element in the `Combobox` component.
**Changes:**
- Renamed and restructured `combobox` classes for better readability
Tested the changes in @warp-ds/react (`fix/add-tests-combo-box` branch)
=> fix(combobox): clean up classes

component-classes/index.d.ts, component-classes/index.js
This PR ensures no classes styling the same CSS properties are being set on the same HTML element in the `Slider` component.
**Changes:**
- Move `s-bg-primary` to the new class`activeTrackEnabled`
- Remove blank space in `track` class
Tested the changes in @warp-ds/react and @warp-ds/vue (`fix/cleanup-slider-classes` branch)
=> fix(slider): clean up classes 

component-classes/index.d.ts, component-classes/index.js
This PR ensures no classes styling the same CSS properties are being set on the same HTML element in the Expandable component.
**Changes:**
- Remove `expandableTitle` (was only used in Vue) and move `s-text` to `expandable` wrapper class
- Remove `expandableInfo` since `info` has been deprecated
- Remove `chevronBox` class that was just setting an empty string
- Rename elements-specific classes and specify that they are only used in elements
- Rename `paddingTop` to `contentWithTitle`
- Replace `h4` with `t4` in the `titleType` class
Tested the changes in @warp-ds/react, @warp-ds/vue and @warp-ds/elements (`fix/cleanup-expandable-component` branch)
=> fix(expandable): clean up classes

component-classes/index.d.ts, component-classes/index.js
This PR ensures no classes styling the same CSS properties are being set on the same HTML element in the Card component.
**Changes:**
- Remove redundant use of `card` in card-classes
- Rename `card` class to `base`
Tested the changes in @warp-ds/react, @warp-ds/vue and @warp-ds/elements (`fix/cleanup-card-classes` branch)
=> fix(card): clean up classes

component-classes/index.d.ts, component-classes/index.js
**Changes:**
1. Restructured component-classes/index.js file:
- Moved all variables to the top of the page
- Sorted all exported objects alphabetically (except for toggle components: `deadToggle` object cannot be sorted alphabetically due to that it uses styling from the `toggle` component that would be declared after `deadToggle`)
2. Renamed classnames for better readability and consistency:
- prefixSuffixWrapperBase —> prefixSuffixWrapper
- box.box —> box.base
- pill.pill —> pill.wrapper
- toaster.toaster —> toaster.base
- tabs.tabContainer —> tabs.container
- tabs.wunderbar —> tabs.selectionIndicator
- tabs.wrapperUnderlined —> tabs.wrapper
- tab.tab —> tab.base
- tab.tabInactive —> tab.inactive
- tab.tabActive —> tab.active
- expandable —> wrapper
- expandable.expandableBox —> …
=> fix: rename classnames and restructure component-classes file

component-classes/index.d.ts, component-classes/index.js
This PR ensures no classes styling the same CSS properties are being set on the same HTML element in the `switchToggle` component.
**Changes:**
- Rename `switchToggle.label` to `switchToggle.base`
- Rename `switchToggle.labelDisabled` to `switchToggle.disabled`
- Add `focusable rounded-full` to `switchToggle.base` that was previously hardcoded in the React `Switch` component
Tested the changes in @warp-ds/react (fix/cleanup-switch-toggle-classes) and @warp-ds/vue (fix/update-classnames)
=> fix(switchtoggle): clean up classes

component-classes/index.d.ts, component-classes/index.js
It should suffice to use `wrapper` and `base` keys, where `wrapper` would style an element which "wraps" a `base`-styled element.
=> refactor(cc): rename keys 'container' & 'unSelected'

component-classes/index.js
The buttonGroupItem should only have border on active when outlined and selected are true.
=> fix(buttongroupitem): set border only on active when outlined and selected are true

component-classes/index.js
Prevent bleeding of background colors in rounded corners and fixes transparent bottom padding issue in Combobox component.
Reported here:
https://sch-chat.slack.com/archives/C04P0GYTHPV/p1724745202595269
=> fix: Background color fixes for Combobox component

resets/resets.js
Disable tooltips on all SVGs on site because of the discussion we had with the a11y team.
This decision is based on our meeting with A11y team, notes here: https://github.com/warp-ds/notes/blob/main/Svg%20titles%2C%20A11y%20%26%20Best%20Practices.md
=> fix: disable svg tooltip on all sites

component-classes/index.js
Fixes [WARP-638](https://nmp-jira.atlassian.net/browse/WARP-638)
Tab's selected border has so far been styled by a "selection-indicator" `span` of the Tabs component. That span's width and position was calculated based on `getBoundingClientRect()` of the child Tab, and after an animation was finished, the correct Tab got its bottom border. That way of indicating the selected tab does not work server-side, which led us to the solution suggested in this PR. By setting the bottom border color of the selected Tab to `s-border-selected` whenever it's active, we ensure it's styled correctly regardless of whether JavaScript is enabled or not. The animation of the span will remain, as this change does not interfere with that.
As a consequence of the suggested change, the selected tab style …
=> fix(tabs): set border on selected tab to fix SSR

index.js, utils.js
Depends on https://github.com/warp-ds/tokens/pull/13
Fixes [WARP-643](https://nmp-jira.atlassian.net/browse/WARP-643)
This PR adds a `--w-dv-` prefix to all dataviz tokens fetched from the @warp-ds/tokens repo and publishes them as `dataviz.css` alongside other Warp brands CSS. 
Also adds a check whether there are any custom tokens files available under `./tokens` directory so the build script doesn't fail.
=> feat: handle dataviz tokens

index.js
Dataline, datatext, datafill, databorder tokens lost the data- prefix. The change was updated in the warp-ds/tokens repo ([see here](https://github.com/warp-ds/tokens/pull/15/files#diff-8e597f6c38d7202a67059e0632eae085882ba015c2c33c7aa31d56765e4d1f59)), but requires a new release in this repo to be updated on Eik servers.
Additionally, I removed the check for oikotie brands from the build script as this brand is already filtered out in [warp-ds/tokens](https://github.com/warp-ds/tokens/blob/main/utils.js#L11).
=> fix(dist): release renamed dataviz CSS variables

README.md
Additionally, updated the README to reflect the current way of generating brand and dataviz CSS files.
=> fix(dataviz): rename 'categorical' to 'category' in text tokens

component-classes/index.d.ts, component-classes/index.js
Adding any classes we remove in v2 into a `backwardsCompatibleClasses` object.
=> fix: add removed class in a backward compatible list
